#!/bin/bash

DIR="$(dirname "$0")"
. "${DIR}/config"

set -v

gcloud builds submit \
  --config scripts/cloudbuild.yaml \
  --substitutions=_SERVICE_NAME="${SERVICE_NAME}",_SERVICE_SRC="${SERVICE_SRC}"