#!/bin/bash

PROJECT_ID="${PROJECT_ID:-events-atamel}"
PROJECT_NUMBER="$(gcloud projects describe "${PROJECT_ID}" --format='value(projectNumber)' --quiet)"
REGION="${REGION:-europe-west1}"
BUCKET_ID="${BUCKET_ID:-amathus-events-atamel-bucket}"
TOPIC_NAME="${TOPIC_NAME:-amathus-events-atamel-topic}"

set_service() {
  echo "$1" "$2"

  # Amathus.Reader
  if [ "$1" == "reader" ]; then
    SERVICE_SRC=Amathus.Reader
    SERVICE_NAME=amathus-reader
  # Amathus.Converter
  elif [ "$1" == "converter" ]; then
    SERVICE_SRC=Amathus.Converter
    SERVICE_NAME=amathus-converter
  # Amathus.Web
  elif [ "$1" == "web" ]; then
    SERVICE_SRC=Amathus.Web
    SERVICE_NAME=amathus-web
  else
    echo "Error: No service specified (use: reader | converter | web)"
    exit 1
  fi

  if [ "$2" == "public" ]; then
    SERVICE_VISIBILITY=allow-unauthenticated
  else
    SERVICE_VISIBILITY=no-allow-unauthenticated
  fi

  echo "PROJECT_ID: ${PROJECT_ID}"
  echo "REGION: ${REGION}"
  echo "SERVICE_NAME: ${SERVICE_NAME}"
  echo "SERVICE_SRC: ${SERVICE_SRC}"
  echo "SERVICE_VISIBILITY: ${SERVICE_VISIBILITY}"
}