#!/bin/bash

DIR="$(dirname "$0")"
. "${DIR}/config"

set_service $1 $2

set -v

gcloud run deploy ${SERVICE_NAME} \
  --image gcr.io/${PROJECT_ID}/${SERVICE_NAME} \
  --region ${REGION} \
  --platform managed \
  --${SERVICE_VISIBILITY} \
  --timeout 900 \
  --memory 2Gi