#!/bin/bash

DIR="$(dirname "$0")"
. "${DIR}/config"

set_service $1

set -v

SERVICE_URL="$(gcloud run services list --platform managed --filter=${SERVICE_NAME} --format='value(URL)')"

gcloud beta scheduler jobs create http amathus-reader-job --schedule "*/10 * * * *" \
   --http-method=GET \
   --uri=${SERVICE_URL}